lok:
  issuer: herre
  key_type: RS256
  public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3zKYtsPl/wsTtX4XQRtBnaTYYXGzqF8uhAourwqvWYPMnQlVbSJGZquVkmljFnRKg1FjOmoEsjIvb9tBtyZuW+oWL06aqArLm2kcCbPofYN8mJnoQdtAxssnJz02gkIYfbFUy/ImBWWq3xQjbleNtN8qGPGaYbo3BIzZv1zwZIddta0MJhBGlGhUO1LsookU6k0OaZcFg1xjUFZgkgTm7DNWUkuEBJwtGvI6W6IF0e2KAXkgp/c77p+5/ZqXwa694+Uoz36Dqsffjho2FtfLwFUfsFvIkB40Pwzd/2Uie9b5W8ocXou3S71+6jgeQZqsB+STnBX/X4Uh7d5uiPSoH
port: 8050
postgres:
  db_name: port_db
  host: daten
  password: 6398045f7711b517ac0aa3c7e6b77a63
  port: 5432
  user: arkitekt
redis:
  host: redis
  port: 6379
server:
  admin:
    email: johannes.roos@u-bordeaux.fr
    password: roos
    username: admin
  debug: true
  hosts:
    - "*"
  secret_key: )bzdzfc2rru2^$_8t%*a14-5rnscto7*d(0dl&1*lywa@ync#zy
dock:
  default_network: dev
