db:
  db_name: port_db
  engine: django.db.backends.postgresql
  host: db
  password: c00f399c94e5d1d0e2d53226a4f384cd
  port: 5432
  username: zippyolivebutterfly
django:
  admin:
    email: admin@admin.com
    password: admin
    username: admin
  debug: false
  hosts:
    - "*"
  secret_key: oljw68pctwwl#y)v1a4k=jbrefv0x+%us@!5aq8z6-#5lys=o!
lok:
  issuer: lok
  key_type: RS256
  public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDGFj0zB7j6KrTRFEP+a2Z7toLEwJ0ROF3qSkq6vo2aK5TGRv+D3V/6VhvM2NgtUIO1iqwvf4XETamhHt2xlVzJyoyMAnAGkwkMyQJpI6wG5g7NtrRc1kkeefWbLBVW+aEI++3ec3eD9PUhnjXbQXJwju8l2ldKg2skw2fZWrjfWo0S0CuvB05nXJ8BmmAo65BBv29gGVywzZEApv/Zu16l6ftCZSEKi/zMbK6YxCekl/h3sfK7uGj6uaab7XSqqANHDZDTSotD5ws8UdMb3IP4/qoJiJm0Lsw5XpmFTt9M+ekiv/9HsWjXtzOd0BpqxynlvF1fWDr0HVnrUCh1XMzn
redis:
  host: redis
  port: 6379
virtualizer:
  allowed_runtimes:
    - nvidia
    - runc
    - wasm
  engine: docker
  network: dev
