postgres:
  host: flabberl
  port: 5432
  user: hello_flabberl
  password: hello_flabberl
  db_name: hello_flabberl

redis:
  host: redis
  port: 6379

server:
  debug: True
  hosts:
    - "*"

security:
  admins:
    - username: demo
      password: demodemo 
      email: demo@demo.com
  secret_key: gagamat5s+_5iyi=*z^zn67xyw&4pv$c0_j^m!aqz6c-q2z8-vht0%gag

herre:
  public_key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvIrkAA1Tr8pLRR08xXEs
    zuyi/+QGRQ3J7o5j7B+HJLv2MWppd+fgoPQYc9nOkZcA9Jizsvm0bqcXe/8zdxaU
    z7bA+nq3hxLolO4q4SXRxNuBIcNrfLizFrWku5csO9ZfS4EXQGOGAWsVE1WbSRBC
    gAcOR8eq8gB0ai4UByB/xGlwobz1bkuXd3jGVN2oeCo7gbij/JaMrOSkh9wX/WqZ
    lbrEWEFfgURENACn45Hm4ojjLepw/b2j7ZrHMQxvY1THi6lZ6bp9NdfkzyE6JhZb
    SVOzd/dHy+gLBx2UuvmovVEhhxzwRJYtPdqlOWuUOjO24AlpPv7j+BSY7eGSzYU5
    oQIDAQAB
    -----END PUBLIC KEY-----
  key_type: RS256
  issuer: herre

