version: "3.4"

services:
  port:
    build: .
    command: bash run.sh
    ports:
      - 8050:8050
    depends_on: 
      - flabberl




networks:
  default:
    external:
      name: dev

