version: "3.4"

services:
  port-dev:
    build: .
    command: bash run.sh
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8055:8055




networks:
  default:
    external:
      name: dev

