version: "3.4"

services:
  port:
    build: .
    command: python manage.py runserver 0.0.0.0:8090
    ports:
      - 8060:8060
    volumes:
      - .:/worskpace:cached
      - /var/run/docker.sock:/var/run/docker.sock 

    env_file:
      - port.env
  flabberl:
    image: postgres:12.6-alpine
    env_file:
      - port.env



networks:
  default:
    external:
      name: dev

