# Generated by Django 3.2.18 on 2023-05-02 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='latests', max_length=400)),
                ('identifier', models.CharField(max_length=4000)),
                ('scopes', models.JSONField(default=list)),
                ('requirements', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('deployed_at', models.DateTimeField(auto_now=True)),
                ('command', models.CharField(default='arkitekt run port', max_length=4000, null=True)),
                ('image', models.CharField(max_length=400)),
                ('entrypoint', models.CharField(default='app', max_length=4000)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Whale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
                ('client_id', models.CharField(max_length=1000)),
                ('token', models.CharField(max_length=10000, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whales', to='haven.deployment')),
            ],
        ),
        migrations.CreateModel(
            name='GithubRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo', models.CharField(max_length=4000)),
                ('user', models.CharField(max_length=4000)),
                ('branch', models.CharField(max_length=4000)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='deployment',
            name='repo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='haven.githubrepo'),
        ),
        migrations.AddConstraint(
            model_name='deployment',
            constraint=models.UniqueConstraint(fields=('identifier', 'version'), name='unique_deployment for version'),
        ),
    ]
