# Generated by Django 3.2.18 on 2023-05-02 11:36

from django.db import migrations, models
import haven.storage


class Migration(migrations.Migration):

    dependencies = [
        ('haven', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='logo',
            field=models.ImageField(blank=True, max_length=1000, null=True, storage=haven.storage.PrivateMediaStorage(), upload_to=''),
        ),
    ]
