# Generated by Django 3.2.18 on 2023-03-31 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haven', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='entrypoint',
            field=models.CharField(default='app', max_length=4000),
        ),
    ]
