# Generated by Django 3.1.7 on 2021-03-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haven', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arkitekt_id', models.CharField(help_text='The corresponding Provider on the Arkitekt Instance', max_length=1000)),
                ('channel', models.CharField(help_text='The channel we  will listen to', max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='porttemplate',
            name='env',
            field=models.JSONField(help_text='Environment parameters for the Port', null=True),
        ),
    ]
