# Generated by Django 3.2.9 on 2021-11-18 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haven', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=4000)),
                ('definition', models.JSONField(default=dict, help_text='The Node this Repo wants to define')),
                ('backend', models.BooleanField(default=False, help_text='Does this Task want to be a BackendApp?')),
                ('scopes', models.JSONField(default=list)),
                ('whale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='haven.whale')),
            ],
        ),
    ]
