# Generated by Django 3.2.9 on 2021-11-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haven', '0002_githubrepo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='githubrepo',
            old_name='url',
            new_name='branch',
        ),
        migrations.AddField(
            model_name='githubrepo',
            name='repo',
            field=models.CharField(default='', max_length=4000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='githubrepo',
            name='user',
            field=models.CharField(default='', max_length=4000),
            preserve_default=False,
        ),
    ]
