# Generated by Django 3.1.7 on 2021-03-05 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haven', '0002_auto_20210304_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortPod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arkitekt_id', models.CharField(help_text='The Corresponding Pod on the Arkitekt Instance', max_length=1000)),
                ('template', models.ForeignKey(help_text='The corresponding Template', on_delete=django.db.models.deletion.CASCADE, to='haven.porttemplate')),
            ],
        ),
    ]
