# Generated by Django 3.2.16 on 2023-01-25 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haven', '0003_reposcan_runtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='whale',
            name='repo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whales', to='haven.reposcan'),
        ),
        migrations.AlterField(
            model_name='reposcan',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='haven.githubrepo'),
        ),
    ]
