# Generated by Django 3.2.9 on 2021-11-18 14:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('haven', '0003_auto_20211118_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrepo',
            name='created_at',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
