# Generated by Django 3.1.7 on 2021-03-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haven', '0003_portpod'),
    ]

    operations = [
        migrations.AddField(
            model_name='portpod',
            name='name',
            field=models.CharField(default='mpompO', help_text='The containers clear-text name', max_length=100),
            preserve_default=False,
        ),
    ]
