# Generated by Django 3.2.19 on 2023-08-29 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haven', '0004_auto_20230829_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='manifest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='haven.manifest'),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='haven.githubrepo'),
        ),
    ]
