# Generated by Django 3.2.9 on 2021-11-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haven', '0004_githubrepo_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whale',
            old_name='env',
            new_name='config',
        ),
        migrations.RemoveField(
            model_name='whale',
            name='namespace',
        ),
        migrations.RemoveField(
            model_name='whale',
            name='repo',
        ),
        migrations.RemoveField(
            model_name='whale',
            name='tag',
        ),
        migrations.AddField(
            model_name='whale',
            name='image',
            field=models.CharField(default='image/jus:nn2', max_length=4000),
            preserve_default=False,
        ),
    ]
