# Generated by Django 3.2.9 on 2021-11-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haven', '0005_auto_20211118_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrepo',
            name='image',
            field=models.CharField(default='jhnnsrs/ome:latest', max_length=400),
        ),
    ]
