# Generated by Django 3.2.9 on 2021-11-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haven', '0006_githubrepo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='whale',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='githubrepo',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
