# Generated by Django 3.2.9 on 2021-11-18 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haven', '0007_auto_20211118_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubrepo',
            name='whale',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='haven.whale'),
        ),
    ]
