# Generated by Django 3.2.10 on 2022-05-18 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haven', '0009_auto_20220518_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='githubrepo',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='githubrepo',
            name='scopes',
        ),
        migrations.RemoveField(
            model_name='githubrepo',
            name='whale',
        ),
    ]
