name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

    
jobs:
  linux_unit:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.12"]
        poetry-version: [1.7]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Run Poetry Install
        run: poetry install --all-extras
      - name: Run Tests
        run: poetry run pytest --cov --cov-report=xml  -k "not integration"
  